version: '3.7'

networks:
  microservice-network:
    driver: bridge

services:

  frontend-microservice:
    image: ghcr.io/studienprojekt-sdp/frontend:latest
    ports:
      - "3000:3000"
    networks:
      - microservice-network

  time-microservice:
    image: ghcr.io/studienprojekt-sdp/timeservice:latest
    networks: 
      - microservice-network

  weather-microservice:
    image: ghcr.io/studienprojekt-sdp/weatherservice:latest
    networks:
      - microservice-network

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 14400 -e REPO_USER=${REPO_USER} -e REPO_PASS:${REPO_PASS}
  